const config = {
  token:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjBlY2M1MDBkNDBlYjBkY2RmYzQyNCIsInNjb3BlcyI6WyJhZG1pbiJdLCJpYXQiOjE3MTgxMDY2NjMsImV4cCI6MTcxODE5MzA2M30.TtBASSCEvEEXJCfDZoyNhTdE4LBAtTK2jIF01wmOXlo",
};

export default config;
